### ISSUE TITLE
Verify window has enough values to process feature vector

### ISSUE THREAD

**Issue by bminor-wsu** [WSU-CASAS/AL#60]
When running feature extraction, we sometimes get `numpy` "mean of empty slice" errors.

I believe this occurs when we are trying to run the feature extraction functions on data when the window is not full size (or at least has only zero or one values?)

## TODO:
- [x] Update `al.py` to reset `count` on each new `al.resetvars()` call (new window)
- [x] Verify resetting `count` on each `al.resetvars()` works properly in `al.extract_features()`
- [x] Update `loc.py` to reset `count` on each new `resetvars()` call (new window)
- [x] Verify resetting `count` on each `resetvars()` works properly in `loc.extract_features()`

## Old Discussion:
It might be good to just check that we have the correct number of points in the window before processing features, otherwise skipping that window. Perhaps something like:
```
len(self.yaw) >= self.conf.samplesize
```

when checking whether to build a window

We will want to make sure this doesn't have a negative effect otherwise, though.

One test case for this (at least with `loc.py`) is the `unittests/test_data/multi_location_test.csv` file.

**Comment by bminor-wsu** [comment]
Technically, the bigger issue here is that the `count` value in `extract_features()` does not get reset when we jump forward in time (or otherwise create a new window and call `resetvars()` at an "irregular" time). So then the `new_window()` check sees that `count` is the right size, but in actuality the window is not full.

Perhaps a better way would be to have a count instead that restarts when the window is cleared.

The main ramification would be in `loc.py` where we currently report count.

**Comment by bminor-wsu** [comment]
For `al.py` at least, we can probably just reset `count` on each new window, as the `count % samplesize` type things will still work the same...

For `loc.py` we'd still want to keep track of the total count - perhaps for now we will just remove that, but add back a `total_count` or something if we want this in either file in the future?
